spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/spring_security?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false

