spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/testmysql?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false

